library(datasets)
plot1 <- read.csv("household_power_consuption.csv")
par(mfrow = c(2, 2))
hist(plot1$Global_active_power, col="red", main="Global Active Power", xlab="Global Active Power (kilowatts)")
plot(plot1$Time, plot1$Global_active_power, ylab="Global Active Power (kilowatts)", xlab="datetime")
plot(plot1$Time, plot1$Sub_metering_1, ylab="Energy sub metering")
lines(plot1$Sub_metering_2, col="red")
lines(plot1$Sub_metering_3, col="blue")
legend("topright", legend=c("Sub_metering_1","Sub_metering_2","Sub_metering_3"), col=c("black","red","blue"), lty=c(1,1,1))
plot(plot1$Time, plot1$Global_reactive_power, ylab="Global Rective Power", xlab="datetime")